function getImagePositioningParams() {
    return {
        r_24: [
            {   id: 'canvas1',
                zIndex: -1, //r_24
                facePositionTopOffset: 100,
                facePositionLeftOffset: 95,
                ratio: 0.80,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(100%) sepia(30%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            },
       
            {   id: 'canvas2',//r_33
                zIndex: -2,
                facePositionTopOffset: 85,
                facePositionLeftOffset: 440,
                ratio: 0.15,
                filter: 'grayscale(100%) sepia(30%)',
                inverseMirror: false,
                faceHeight: 400,
                faceWidth: 400,
                boxXOffset: -120,
                boxYOffset: -120,
                boxWidthOffset: 260,
                boxHeightOffset: 260,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas3',//r_33
                zIndex: -3,
                facePositionTopOffset: 100,
                facePositionLeftOffset: 575,
                ratio: 0.15,
                filter: 'grayscale(100%) sepia(30%)',
                inverseMirror: false,
                faceHeight: 400,
                faceWidth: 400,
                boxXOffset: -120,
                boxYOffset: -120,
                boxWidthOffset: 260,
                boxHeightOffset: 260,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas4',//r_21
                zIndex: -4,
                facePositionTopOffset: 120,
                facePositionLeftOffset: 850,
                ratio: 0.35,
                filter: 'grayscale(100%) sepia(70%)',
                inverseMirror: false,
                faceHeight: 400,
                faceWidth: 400,
                boxXOffset: -120,
                boxYOffset: -120,
                boxWidthOffset: 260,
                boxHeightOffset: 260,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas5',//r_19_1
                zIndex: -5,
                facePositionTopOffset: 355,
                facePositionLeftOffset: 395,
                ratio: 0.10,
                filter: 'grayscale(100%) sepia(10%)',
                inverseMirror: false,
                faceHeight: 400,
                faceWidth: 400,
                boxXOffset: -240,
                boxYOffset: -240,
                boxWidthOffset: 520,
                boxHeightOffset: 520,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
             {   id: 'canvas6',//r_19_2
                zIndex: -7,
                facePositionTopOffset: 345,
                facePositionLeftOffset: 430,
                ratio: 0.10,
                filter: 'grayscale(100%) sepia(10%)',
                inverseMirror: false,
                 faceHeight: 400,
                 faceWidth: 400,
                 boxXOffset: -240,
                 boxYOffset: -240,
                 boxWidthOffset: 520,
                 boxHeightOffset: 520,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                 canvas: undefined
            },
             {   id: 'canvas7',//r_19_3
                zIndex: -6,
                facePositionTopOffset: 360,
                facePositionLeftOffset: 450,
                ratio: 0.10,
                filter: 'grayscale(100%) sepia(10%)',
                inverseMirror: false,
                 faceHeight: 400,
                 faceWidth: 400,
                 boxXOffset: -240,
                 boxYOffset: -240,
                 boxWidthOffset: 520,
                 boxHeightOffset: 520,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                 canvas: undefined
            },
             {   id: 'canvas8',//r_19_4
                zIndex: -8,
                facePositionTopOffset: 485,
                facePositionLeftOffset: 490,
                ratio: 0.10,
                filter: 'grayscale(100%) sepia(10%)',
                inverseMirror: false,
                 faceHeight: 400,
                 faceWidth: 400,
                 boxXOffset: -240,
                 boxYOffset: -240,
                 boxWidthOffset: 520,
                 boxHeightOffset: 520,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                 canvas: undefined
            },
            {   id: 'canvas8',//r_19_4
                zIndex: -8,
                facePositionTopOffset: 355,
                facePositionLeftOffset: 495,
                ratio: 0.10,
                filter: 'grayscale(100%) sepia(10%)',
                inverseMirror: false,
                faceHeight: 400,
                faceWidth: 400,
                boxXOffset: -240,
                boxYOffset: -240,
                boxWidthOffset: 520,
                boxHeightOffset: 520,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas9',//r_19_5
                zIndex: -9,
                facePositionTopOffset: 355,
                facePositionLeftOffset: 540,
                ratio: 0.10,
                filter: 'grayscale(100%) sepia(10%)',
                inverseMirror: false,
                faceHeight: 400,
                faceWidth: 400,
                boxXOffset: -240,
                boxYOffset: -240,
                boxWidthOffset: 520,
                boxHeightOffset: 520,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas10',//r_19_6
                zIndex: -10,
                facePositionTopOffset: 355,
                facePositionLeftOffset: 585,
                ratio: 0.08,
                filter: 'grayscale(100%) sepia(10%)',
                inverseMirror: false,
                faceHeight: 400,
                faceWidth: 400,
                boxXOffset: -240,
                boxYOffset: -240,
                boxWidthOffset: 520,
                boxHeightOffset: 520,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas11',//r_19_7
                zIndex: -11,
                facePositionTopOffset: 363,
                facePositionLeftOffset: 605,
                ratio: 0.10,
                filter: 'grayscale(100%) sepia(10%)',
                inverseMirror: false,
                faceHeight: 400,
                faceWidth: 400,
                boxXOffset: -240,
                boxYOffset: -240,
                boxWidthOffset: 520,
                boxHeightOffset: 520,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas12',//r_10_1
                zIndex: -12,
                facePositionTopOffset: 600,
                facePositionLeftOffset: 455,
                ratio: 0.15,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(100%) sepia(70%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas13',//r_10_2
                zIndex: -13,
                facePositionTopOffset: 600,
                facePositionLeftOffset: 495,
                ratio: 0.15,
                filter: 'grayscale(100%) sepia(70%)',
                inverseMirror: false,
                faceHeight: 200,
                faceWidth: 200,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
             {   id: 'canvas14',//r_10_3
                zIndex: -14,
                facePositionTopOffset: 620,
                facePositionLeftOffset: 525,
                ratio: 0.15,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(100%) sepia(70%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                 canvas: undefined
            },
            {   id: 'canvas15',//r_10_4
                zIndex: -15,
                facePositionTopOffset: 600,
                facePositionLeftOffset: 560,
                ratio: 0.15,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(100%) sepia(70%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas16',//r_22_2
                zIndex: -16,
                facePositionTopOffset: 575,
                facePositionLeftOffset: 870,
                ratio: 0.25,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas17',//r_22_1
                zIndex: -17,
                facePositionTopOffset: 530,
                facePositionLeftOffset: 835,
                ratio: 0.35,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas18',//r_02_1 //cuplu rama maro
                zIndex: -18,
                facePositionTopOffset: 900,
                facePositionLeftOffset: 140,
                ratio: 0.20,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(100%) sepia(20%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas19',//r_02_2
                zIndex: -19,
                facePositionTopOffset: 895,
                facePositionLeftOffset: 185,
                ratio: 0.15,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(100%) sepia(20%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas20',//r_11_1 //doi tipi rama lemn 
                zIndex: -15,
                facePositionTopOffset: 880,
                facePositionLeftOffset: 440,
                ratio: 0.25,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas21',//r_11_2
                zIndex: -21,
                facePositionTopOffset: 890,
                facePositionLeftOffset: 550,
                ratio: 0.25,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas22',//r_03 masina
                zIndex: -22,
                facePositionTopOffset: 1180,
                facePositionLeftOffset: 240,
                ratio: 0.12,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
            {   id: 'canvas23',//r_12_1 poza clown - femeia 
                zIndex: -23,
                facePositionTopOffset: 1200,
                facePositionLeftOffset: 565,
                ratio: 0.20,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas24',//r_12_1 poza clown - barbat 
                zIndex: -24,
                facePositionTopOffset: 1190,
                facePositionLeftOffset: 525,
                ratio: 0.20,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas25',//r_12_1 poza clown - clown 
                zIndex: -25,
                facePositionTopOffset: 1175,
                facePositionLeftOffset: 460,
                ratio: 0.15,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
             {   id: 'canvas26',//r_04_1 familia
                zIndex: -26,
                facePositionTopOffset: 1475,
                facePositionLeftOffset: 80,
                ratio: 0.25,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                 canvas: undefined
            },
            {   id: 'canvas27',//r_04_2 familia
                zIndex: -27,
                facePositionTopOffset: 1500,
                facePositionLeftOffset: 145,
                ratio: 0.20,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas28',//r_04_3 familia
                zIndex: -28,
                facePositionTopOffset: 1525,
                facePositionLeftOffset: 180,
                ratio: 0.17,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas29',//r_04_4 familia
                zIndex: -29,
                facePositionTopOffset: 1480,
                facePositionLeftOffset: 225,
                ratio: 0.20,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
            {   id: 'canvas30',//r_23_1 femei rama maro 
                zIndex: -30,
                facePositionTopOffset: 1345,
                facePositionLeftOffset: 805,
                ratio: 0.35,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(100%) sepia(30%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas31',//r_23_2 femei rama maro 
                zIndex: -31,
                facePositionTopOffset: 1385,
                facePositionLeftOffset: 876,
                ratio: 0.35,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(100%) sepia(30%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            }, 
            {   id: 'canvas32',//r_13_2 femei fotoliu 
                zIndex: -32,
                facePositionTopOffset: 1730,
                facePositionLeftOffset: 555,
                ratio: 0.17,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(30%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
            {   id: 'canvas33',//r_13_2 femei fotoliu [poza mica]
                zIndex: -33,
                facePositionTopOffset: 1720,
                facePositionLeftOffset: 436,
                ratio: 0.20,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(100%) sepia(30%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
             {   id: 'canvas34',//r_05_1 rama dubla
                zIndex: -34,
                facePositionTopOffset: 1940,
                facePositionLeftOffset: 58,
                ratio: 0.15,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                 canvas: undefined
            }, 
            {   id: 'canvas35',//r_05_2 rama dubla
                zIndex: -35,
                facePositionTopOffset: 1935,
                facePositionLeftOffset: 97,
                ratio: 0.15,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
            {   id: 'canvas36',//r_05_3 rama dubla
                zIndex: -36,
                facePositionTopOffset: 1922,
                facePositionLeftOffset: 243,
                ratio: 0.20,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
            {   id: 'canvas37',//r_14 rama argintie floricele
                zIndex: -37,
                facePositionTopOffset: 1975,
                facePositionLeftOffset: 480,
                ratio: 0.35,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
            {   id: 'canvas38',//r_26 rama aurie ovala
                zIndex: -38,
                facePositionTopOffset: 2045,
                facePositionLeftOffset: 760,
                ratio: 1.2,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(20%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
            {   id: 'canvas39',//r_15_1 rama argintie doua tipe
                zIndex: -39,
                facePositionTopOffset: 2270,
                facePositionLeftOffset: 440,
                ratio: 0.5,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(10%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
             {   id: 'canvas40',//r_15_2 rama argintie doua tipe
                zIndex: -40,
                facePositionTopOffset: 2260,
                facePositionLeftOffset: 540,
                ratio: 0.45,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(10%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                 canvas: undefined
            }, 
            {   id: 'canvas41',//r_16 rama perdea muste
                zIndex: -41,
                facePositionTopOffset: 2855,
                facePositionLeftOffset: 467,
                ratio: 0.25,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
            {   id: 'canvas42',//r_27_1 rama alba
                zIndex: -42,
                facePositionTopOffset: 2550,
                facePositionLeftOffset: 840,
                ratio: 0.6,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
             {   id: 'canvas43',//r_27_2 rama alba
                zIndex: -43,
                facePositionTopOffset: 2750,
                facePositionLeftOffset: 760,
                ratio: 0.45,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(30%)',
                inverseMirror: true,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                 canvas: undefined
            }, 
            {   id: 'canvas44',//r_27_3 rama alba
                zIndex: -44,
                facePositionTopOffset: 2755,
                facePositionLeftOffset: 925,
                ratio: 0.45,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(30%)',
                inverseMirror: true,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
            {   id: 'canvas45',//r_27_3 rama octagon lemn
                zIndex: 45,
                facePositionTopOffset: 2600,
                facePositionLeftOffset: 160,
                ratio: 0.20,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(30%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
            {   id: 'canvas45',//r_27_3 rama octagon lemn
                zIndex: -45,
                facePositionTopOffset: 2583,
                facePositionLeftOffset: 195,
                ratio: 0.20,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(30%)',
                inverseMirror: true,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
            {   id: 'canvas46',//r_07 rama barbat fotoliu
                zIndex: -46,
                facePositionTopOffset: 2975,
                facePositionLeftOffset: 140,
                ratio: 0.35,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: true,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            }, 
             {   id: 'canvas47',//r_30 rama cuplu visiniu
                zIndex: -47,
                facePositionTopOffset: 3230,
                facePositionLeftOffset: 150,
                ratio: 0.20,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            }, 
             {   id: 'canvas48',//r_30_2 rama cuplu visiniu
                zIndex: -48,
                facePositionTopOffset: 3250,
                facePositionLeftOffset: 120,
                ratio: 0.20,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            }, 
             {   id: 'canvas49',//r_17_1 rama cuplu batran
                zIndex: -49,
                facePositionTopOffset: 3210,
                facePositionLeftOffset: 477,
                ratio: 0.30,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            }, 
             {   id: 'canvas50',//r_17_2 rama cuplu batran
                zIndex: -50,
                facePositionTopOffset: 3200,
                facePositionLeftOffset: 524,
                ratio: 0.35,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: true,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
            {   id: 'canvas51',//r_18 mana
                zIndex: -51,
                facePositionTopOffset: 3493,
                facePositionLeftOffset: 544,
                ratio: 0.15,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            }, 
            {   id: 'canvas52',//r_28_1 femei alb negru mare 
                zIndex: -53,
                facePositionTopOffset: 3325,
                facePositionLeftOffset: 775,
                ratio: 1.2,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(100%) sepia(30%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            }, 
            {   id: 'canvas53',//r_28_2 femei alb negru mic 
                zIndex: -52,
                facePositionTopOffset: 3550,
                facePositionLeftOffset: 847,
                ratio: 0.75,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(100%) sepia(60%)',
                inverseMirror: true,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            }, 





            
        ]
    }
};
