function getImagePositioningParams() {
    return {
        r_24: [
            {   id: 'canvas1',
                zIndex: -1, //r_24
                facePositionTopOffset: 115,
                facePositionLeftOffset: 120,
                ratio: 0.80,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(100%) sepia(30%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            },
       
            {   id: 'canvas2',//r_33
                zIndex: -2,
                facePositionTopOffset: 85,
                facePositionLeftOffset: 440,
                ratio: 0.15,
                filter: 'grayscale(100%) sepia(30%)',
                inverseMirror: false,
                faceHeight: 400,
                faceWidth: 400,
                boxXOffset: -120,
                boxYOffset: -120,
                boxWidthOffset: 260,
                boxHeightOffset: 260,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas3',//r_33
                zIndex: -3,
                facePositionTopOffset: 100,
                facePositionLeftOffset: 575,
                ratio: 0.15,
                filter: 'grayscale(100%) sepia(30%)',
                inverseMirror: false,
                faceHeight: 400,
                faceWidth: 400,
                boxXOffset: -120,
                boxYOffset: -120,
                boxWidthOffset: 260,
                boxHeightOffset: 260,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas4',//r_21
                zIndex: -4,
                facePositionTopOffset: 120,
                facePositionLeftOffset: 850,
                ratio: 0.35,
                filter: 'grayscale(100%) sepia(70%)',
                inverseMirror: false,
                faceHeight: 400,
                faceWidth: 400,
                boxXOffset: -120,
                boxYOffset: -120,
                boxWidthOffset: 260,
                boxHeightOffset: 260,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas5',//r_19_1
                zIndex: -5,
                facePositionTopOffset: 355,
                facePositionLeftOffset: 395,
                ratio: 0.10,
                filter: 'grayscale(100%) sepia(10%)',
                inverseMirror: false,
                faceHeight: 400,
                faceWidth: 400,
                boxXOffset: -240,
                boxYOffset: -240,
                boxWidthOffset: 520,
                boxHeightOffset: 520,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
             {   id: 'canvas6',//r_19_2
                zIndex: -7,
                facePositionTopOffset: 345,
                facePositionLeftOffset: 430,
                ratio: 0.10,
                filter: 'grayscale(100%) sepia(10%)',
                inverseMirror: false,
                 faceHeight: 400,
                 faceWidth: 400,
                 boxXOffset: -240,
                 boxYOffset: -240,
                 boxWidthOffset: 520,
                 boxHeightOffset: 520,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                 canvas: undefined
            },
             {   id: 'canvas7',//r_19_3
                zIndex: -6,
                facePositionTopOffset: 360,
                facePositionLeftOffset: 450,
                ratio: 0.10,
                filter: 'grayscale(100%) sepia(10%)',
                inverseMirror: false,
                 faceHeight: 400,
                 faceWidth: 400,
                 boxXOffset: -240,
                 boxYOffset: -240,
                 boxWidthOffset: 520,
                 boxHeightOffset: 520,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                 canvas: undefined
            },
             {   id: 'canvas8',//r_19_4
                zIndex: -8,
                facePositionTopOffset: 485,
                facePositionLeftOffset: 490,
                ratio: 0.10,
                filter: 'grayscale(100%) sepia(10%)',
                inverseMirror: false,
                 faceHeight: 400,
                 faceWidth: 400,
                 boxXOffset: -240,
                 boxYOffset: -240,
                 boxWidthOffset: 520,
                 boxHeightOffset: 520,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                 canvas: undefined
            },
            {   id: 'canvas8',//r_19_4
                zIndex: -8,
                facePositionTopOffset: 355,
                facePositionLeftOffset: 495,
                ratio: 0.10,
                filter: 'grayscale(100%) sepia(10%)',
                inverseMirror: false,
                faceHeight: 400,
                faceWidth: 400,
                boxXOffset: -240,
                boxYOffset: -240,
                boxWidthOffset: 520,
                boxHeightOffset: 520,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas9',//r_19_5
                zIndex: -9,
                facePositionTopOffset: 355,
                facePositionLeftOffset: 540,
                ratio: 0.10,
                filter: 'grayscale(100%) sepia(10%)',
                inverseMirror: false,
                faceHeight: 400,
                faceWidth: 400,
                boxXOffset: -240,
                boxYOffset: -240,
                boxWidthOffset: 520,
                boxHeightOffset: 520,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas10',//r_19_6
                zIndex: -10,
                facePositionTopOffset: 355,
                facePositionLeftOffset: 585,
                ratio: 0.08,
                filter: 'grayscale(100%) sepia(10%)',
                inverseMirror: false,
                faceHeight: 400,
                faceWidth: 400,
                boxXOffset: -240,
                boxYOffset: -240,
                boxWidthOffset: 520,
                boxHeightOffset: 520,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas11',//r_19_7
                zIndex: -11,
                facePositionTopOffset: 363,
                facePositionLeftOffset: 605,
                ratio: 0.10,
                filter: 'grayscale(100%) sepia(10%)',
                inverseMirror: false,
                faceHeight: 400,
                faceWidth: 400,
                boxXOffset: -240,
                boxYOffset: -240,
                boxWidthOffset: 520,
                boxHeightOffset: 520,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas12',//r_10_1
                zIndex: -12,
                facePositionTopOffset: 605,
                facePositionLeftOffset: 460,
                ratio: 0.15,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(100%) sepia(70%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas13',//r_10_2
                zIndex: -13,
                facePositionTopOffset: 590,
                facePositionLeftOffset: 490,
                ratio: 0.15,
                filter: 'grayscale(100%) sepia(70%)',
                inverseMirror: false,
                faceHeight: 200,
                faceWidth: 200,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
             {   id: 'canvas14',//r_10_3
                zIndex: -14,
                facePositionTopOffset: 620,
                facePositionLeftOffset: 520,
                ratio: 0.15,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(100%) sepia(70%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                 canvas: undefined
            },
            {   id: 'canvas15',//r_10_4
                zIndex: -15,
                facePositionTopOffset: 590,
                facePositionLeftOffset: 560,
                ratio: 0.15,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(100%) sepia(70%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas16',//r_22_2
                zIndex: -16,
                facePositionTopOffset: 575,
                facePositionLeftOffset: 870,
                ratio: 0.25,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas17',//r_22_1
                zIndex: -17,
                facePositionTopOffset: 530,
                facePositionLeftOffset: 835,
                ratio: 0.35,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas18',//r_02_1 //cuplu rama maro
                zIndex: -18,
                facePositionTopOffset: 900,
                facePositionLeftOffset: 145,
                ratio: 0.18,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(100%) sepia(20%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas19',//r_02_2
                zIndex: -19,
                facePositionTopOffset: 895,
                facePositionLeftOffset: 190,
                ratio: 0.17,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(100%) sepia(20%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas20',//r_11_1 //doi tipi rama lemn 
                zIndex: -15,
                facePositionTopOffset: 873,
                facePositionLeftOffset: 443,
                ratio: 0.25,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas21',//r_11_2
                zIndex: -21,
                facePositionTopOffset: 880,
                facePositionLeftOffset: 545,
                ratio: 0.28,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas22',//r_03 masina
                zIndex: -22,
                facePositionTopOffset: 1165,
                facePositionLeftOffset: 240,
                ratio: 0.07,
                faceHeight: 400,
                faceWidth: 400,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -120,
                boxYOffset: -120,
                boxWidthOffset: 260,
                boxHeightOffset: 260,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
            {   id: 'canvas23',//r_12_1 poza clown - femeia 
                zIndex: -24,
                facePositionTopOffset: 1185,
                facePositionLeftOffset: 555,
                ratio: 0.15,
                faceHeight: 400,
                faceWidth: 400,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -120,
                boxYOffset: -120,
                boxWidthOffset: 260,
                boxHeightOffset: 260,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas24',//r_12_1 poza clown - barbat 
                zIndex: -23,
                facePositionTopOffset: 1175,
                facePositionLeftOffset: 520,
                ratio: 0.23,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas25',//r_12_1 poza clown - clown 
                zIndex: -25,
                facePositionTopOffset: 1160,
                facePositionLeftOffset: 455,
                ratio: 0.18,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                rotate: 'rotate(350deg)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas251',//r_12_1 poza clown - pers in spate
                zIndex: -125,
                facePositionTopOffset: 1155,
                facePositionLeftOffset: 575,
                ratio: 0.1,
                faceHeight: 400,
                faceWidth: 400,
                filter: 'grayscale(0%) sepia(0%)',
                rotate: 'rotate(10deg)',
                inverseMirror: false,
                boxXOffset: -120,
                boxYOffset: -120,
                boxWidthOffset: 260,
                boxHeightOffset: 260,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
             {   id: 'canvas26',//r_04_1 familia
                zIndex: -26,
                facePositionTopOffset: 1456,
                facePositionLeftOffset: 80,
                ratio: 0.3,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                 canvas: undefined
            },
            {   id: 'canvas27',//r_04_2 familia
                zIndex: -27,
                facePositionTopOffset: 1481,
                facePositionLeftOffset: 145,
                ratio: 0.25,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas28',//r_04_3 familia
                zIndex: -28,
                facePositionTopOffset: 1506,
                facePositionLeftOffset: 185,
                ratio: 0.23,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas29',//r_04_4 familia
                zIndex: -29,
                facePositionTopOffset: 1466,
                facePositionLeftOffset: 225,
                ratio: 0.25,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
            {   id: 'canvas30',//r_23_1 femei rama maro 
                zIndex: -30,
                facePositionTopOffset: 1335,
                facePositionLeftOffset: 800,
                ratio: 0.33,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(100%) sepia(30%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas31',//r_23_2 femei rama maro 
                zIndex: -31,
                facePositionTopOffset: 1375,
                facePositionLeftOffset: 870,
                ratio: 0.35,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(100%) sepia(30%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            }, 
            {   id: 'canvas32',//r_13_2 femei fotoliu 
                zIndex: -32,
                facePositionTopOffset: 1681,
                facePositionLeftOffset: 535,
                ratio: 0.17,
                faceHeight: 400,
                faceWidth: 400,
                filter: 'grayscale(0%) sepia(30%)',
                inverseMirror: false,
                boxXOffset: -240,
                boxYOffset: -240,
                boxWidthOffset: 520,
                boxHeightOffset: 520,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
            {   id: 'canvas33',//r_13_2 femei fotoliu [poza mica]
                zIndex: -33,
                facePositionTopOffset: 1671,
                facePositionLeftOffset: 410,
                ratio: 0.23,
                faceHeight: 400,
                faceWidth: 400,
                filter: 'grayscale(100%) sepia(30%)',
                inverseMirror: false,
                boxXOffset: -240,
                boxYOffset: -240,
                boxWidthOffset: 520,
                boxHeightOffset: 520,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
             {   id: 'canvas34',//r_05_1 rama dubla
                zIndex: -34,
                facePositionTopOffset: 1910,
                facePositionLeftOffset: 65,
                ratio: 0.07,
                faceHeight: 400,
                faceWidth: 400,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                 canvas: undefined
            }, 
            {   id: 'canvas35',//r_05_2 rama dubla
                zIndex: -35,
                facePositionTopOffset: 1920,
                facePositionLeftOffset: 97,
                ratio: 0.07,
                faceHeight: 400,
                faceWidth: 400,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
            {   id: 'canvas36',//r_05_3 rama dubla
                zIndex: -36,
                facePositionTopOffset: 1895,
                facePositionLeftOffset: 245,
                ratio: 0.1,
                faceHeight: 400,
                faceWidth: 400,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
            {   id: 'canvas37',//r_14 rama argintie floricele
                zIndex: -37,
                facePositionTopOffset: 1945,
                facePositionLeftOffset: 505,
                ratio: 0.2,
                faceHeight: 400,
                faceWidth: 400,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -120,
                boxYOffset: -120,
                boxWidthOffset: 260,
                boxHeightOffset: 260,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
            {   id: 'canvas38',//r_26 rama aurie ovala
                zIndex: -38,
                facePositionTopOffset: 2060,
                facePositionLeftOffset: 785,
                ratio: 1.0,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(20%)',
                inverseMirror: false,
                rotate: 'rotate(20deg)',
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
            {   id: 'canvas39',//r_15_1 rama argintie doua tipe
                zIndex: -39,
                facePositionTopOffset: 2250,
                facePositionLeftOffset: 440,
                ratio: 0.5,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(10%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
             {   id: 'canvas40',//r_15_2 rama argintie doua tipe
                zIndex: -40,
                facePositionTopOffset: 2235,
                facePositionLeftOffset: 540,
                ratio: 0.45,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(10%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                 canvas: undefined
            }, 
            {   id: 'canvas41',//r_16 rama perdea muste
                zIndex: -41,
                facePositionTopOffset: 2825,
                facePositionLeftOffset: 455,
                ratio: 0.2,
                faceHeight: 400,
                faceWidth: 400,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -120,
                boxYOffset: -120,
                boxWidthOffset: 260,
                boxHeightOffset: 260,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
            {   id: 'canvas42',//r_27_1 rama alba
                zIndex: -42,
                facePositionTopOffset: 2520,
                facePositionLeftOffset: 840,
                ratio: 0.6,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
             {   id: 'canvas43',//r_27_2 rama alba
                zIndex: -43,
                facePositionTopOffset: 2720,
                facePositionLeftOffset: 750,
                ratio: 0.45,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(30%)',
                inverseMirror: true,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                 canvas: undefined
            }, 
            {   id: 'canvas44',//r_27_3 rama alba
                zIndex: -44,
                facePositionTopOffset: 2730,
                facePositionLeftOffset: 915,
                ratio: 0.45,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(30%)',
                inverseMirror: true,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
            {   id: 'canvas45',//r_06_1 rama octagon lemn
                zIndex: -45,
                facePositionTopOffset: 2555,
                facePositionLeftOffset: 195,
                ratio: 0.22,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(30%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            },
            {   id: 'canvas46',//r_07 rama barbat fotoliu
                zIndex: -46,
                facePositionTopOffset: 2955,
                facePositionLeftOffset: 145,
                ratio: 0.35,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                rotate: 'rotate(10deg)',
                inverseMirror: true,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            }, 
             {   id: 'canvas47',//r_30 rama cuplu visiniu
                zIndex: -47,
                facePositionTopOffset: 3190,
                facePositionLeftOffset: 140,
                ratio: 0.19,
                faceHeight: 400,
                faceWidth: 400,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -120,
                boxYOffset: -120,
                boxWidthOffset: 260,
                boxHeightOffset: 260,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            },
             {   id: 'canvas49',//r_17_1 rama cuplu batran
                zIndex: -49,
                facePositionTopOffset: 3180,
                facePositionLeftOffset: 482,
                ratio: 0.3,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -30,
                boxYOffset: -30,
                boxWidthOffset: 70,
                boxHeightOffset: 70,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            }, 
             {   id: 'canvas50',//r_17_2 rama cuplu batran
                zIndex: -50,
                facePositionTopOffset: 3170,
                facePositionLeftOffset: 525,
                 rotate: 'rotate(340deg)',
                ratio: 0.35,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: true,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200,
                canvas: undefined
            }, 
            {   id: 'canvas51',//r_18 mana
                zIndex: -51,
                facePositionTopOffset: 3480,
                facePositionLeftOffset: 544,
                ratio: 0.15,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            }, 
            {   id: 'canvas52',//r_28_1 femei alb negru mare 
                zIndex: -53,
                facePositionTopOffset: 3325,
                facePositionLeftOffset: 815,
                ratio: 1.2,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(100%) sepia(30%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            }, 
            {   id: 'canvas53',//r_28_2 femei alb negru mic 
                zIndex: -52,
                facePositionTopOffset: 3530,
                facePositionLeftOffset: 847,
                ratio: 0.75,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(100%) sepia(60%)',
                inverseMirror: true,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            },
            {   id: 'canvas54',//r_29 cos fructe
                zIndex: -54,
                facePositionTopOffset: 3750,
                facePositionLeftOffset: 865,
                ratio: 0.35,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(100%) sepia(60%)',
                inverseMirror: true,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            },
            {   id: 'canvas55',//r_20 MOTO
                zIndex: -55,
                facePositionTopOffset: 4250,
                facePositionLeftOffset: 500,
                ratio: 0.3,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(100%) sepia(60%)',
                inverseMirror: true,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            },
            {   id: 'canvas56',//r_08  orchestra
                zIndex: -56,
                facePositionTopOffset: 3465,
                facePositionLeftOffset: 75,
                ratio: 0.3,
                faceHeight: 200,
                faceWidth: 200,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -60,
                boxYOffset: -60,
                boxWidthOffset: 130,
                boxHeightOffset: 130,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            },
            {   id: 'canvas57',//r_08 orchestra
                zIndex: -57,
                facePositionTopOffset: 3495,
                facePositionLeftOffset: 135,
                ratio: 0.13,
                faceHeight: 400,
                faceWidth: 400,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -120,
                boxYOffset: -120,
                boxWidthOffset: 260,
                boxHeightOffset: 260,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            },
            {   id: 'canvas58',//r_08 orchestra
                zIndex: -58,
                facePositionTopOffset: 3500,
                facePositionLeftOffset: 190,
                ratio: 0.15,
                faceHeight: 400,
                faceWidth: 400,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -120,
                boxYOffset: -120,
                boxWidthOffset: 260,
                boxHeightOffset: 260,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            },
            {   id: 'canvas59',//r_08 orchestra
                zIndex: -59,
                facePositionTopOffset: 3410,
                facePositionLeftOffset: 250,
                ratio: 0.19,
                faceHeight: 400,
                faceWidth: 400,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -120,
                boxYOffset: -120,
                boxWidthOffset: 260,
                boxHeightOffset: 260,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            },
            {   id: 'canvas60',//r_08 piano girl
                zIndex: -60,
                facePositionTopOffset: 3775,
                facePositionLeftOffset: 175,
                ratio: 0.25,
                faceHeight: 400,
                faceWidth: 400,
                filter: 'grayscale(0%) sepia(0%)',
                inverseMirror: false,
                boxXOffset: -120,
                boxYOffset: -120,
                boxWidthOffset: 260,
                boxHeightOffset: 260,
                //do not edit below
                actualVideoHeight: 200,
                actualVideoWidth: 200
            }
        ]
    }
};
